# Generated by Django 5.2.7 on 2025-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Нужна доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата картой'), ('cod', 'Наличными/картой при получении')], default='card', max_length=10),
        ),
    ]
